name: Auto Update
on:
  schedule:
    - cron: '0 * * * *' # هيحدث الشيت كل ساعة بالظبط
  workflow_dispatch: # زرار تشغيل يدوي للتجربة
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: {python-version: '3.9'}
      - name: Run Update
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          pip install requests gspread oauth2client
          python main.py
